# --------------------
# Define default values
# --------------------

# ==================== Alas ====================

Alas:
  Emulator:
    ScreenshotMethod: scrcpy

# ==================== Daily ====================

# DailyQuest:
#   Scheduler:
#     Enable: true
# BattlePass:
#   Scheduler:
#     Enable: true
# Assignment:
#   Scheduler:
#     Enable: true
# Freebies:
#   Scheduler:
#     Enable: false
Expedition:
  Scheduler:
    Enable: true
Beach:
  Scheduler:
    Enable: true
TacticalAcademy:
  Scheduler:
    Enable: true
MainLine:
  Scheduler:
    Enable: false


# ==================== Weekly ====================

# Weekly:
#   DungeonSupport:
#     Use: do_not_use
