# --------------------
# Define non-modifiable values
# --------------------


# ==================== Alas ====================

Alas:
  Emulator:
    ControlMethod: MaaTouch
  Optimization:
    ScreenshotInterval: 0.2
    CombatScreenshotInterval: 1.0
Restart:
  Scheduler:
    Enable:
      type: state
      value: true
      option: [ true, ]
      option_bold: [ true, ]
    ServerUpdate: 04:00

# ==================== Daily ====================

Dungeon:
  Scheduler:
    Enable:
      type: checkbox
      value: false
      option: [ true,false ]
      option_bold: [ true, ]
      display: display
  DungeonSupport:
    Use:
      option: [ when_daily, always_use ]
DailyQuest:
  Scheduler:
    Enable:
      type: checkbox
      value: false
      option: [ true, false ]
      option_bold: [ true, ]
      display: display
BattlePass:
  Scheduler:
    Enable:
      type: checkbox
      value: false
      option: [ true, false ]
      option_bold: [ true, ]
      display: display
Assignment:
  Scheduler:
    Enable:
      type: checkbox
      value: false
      option: [ true, false ]
      option_bold: [ true, ]
      display: display
DataUpdate:
  Scheduler:
    Enable:
      type: checkbox
      value: true
      option: [ true,false ]
      option_bold: [ true, ]
      display: display
Beach:
  Scheduler:
    Enable:
      style: 'display: block'

# ==================== Weekly ====================

Weekly:
  DungeonSupport:
    Use:
      option: [ always_use, do_not_use ]
Ornament:
  DungeonSupport:
    Use:
      option: [ when_daily, always_use ]
