from module.base.button import Button, ButtonWrapper,ItemWrapper

TASK_DAILY_FINAL=ButtonWrapper(
    name='TASK_DAILY_FINAL',
    share=Button.default_init(
        area=(1055,131,1202,179),color=(209,191,105),
        file='./assets/share/task/TASK_DAILY_FINAL.png'
    )
)
TASK_COLLECT_ALL=ButtonWrapper(
    name='TASK_COLLECT_ALL',
    share=Button.default_init(
        area=(1037,628,1221,677),color=(193,176,93),
        file='./assets/share/task/TASK_COLLECT_ALL.png'
    )
)
TASK_COLLECT_ALL_DISABLED=ButtonWrapper(
    name='TASK_COLLECT_ALL_DISABLED',
    share=Button.default_init(
        area=(1037,628,1221,677),color=(161,158,130),
        file='./assets/share/task/TASK_COLLECT_ALL_DISABLED.png'
    )
)
TASK_DAILY_FINAL_FINISHED=ButtonWrapper(
    name='TASK_DAILY_FINAL_FINISHED',
    share=Button.default_init(
        area=(1080,139,1166,167),color=(73,73,73),
        file='./assets/share/task/TASK_DAILY_FINAL_FINISHED.png'
    )
)
TASK_DAILY_FINAL_GO=ButtonWrapper(
    name='TASK_DAILY_FINAL_GO',
    share=Button.default_init(
        area=(1105,140,1151,169),color=(116,116,116),
        file='./assets/share/task/TASK_DAILY_FINAL_GO.png'
    )
)
LUCKY_DRAW=ButtonWrapper(
    name='LUCKY_DRAW',
    share=Button.default_init(
        area=(270,609,354,633),color=(135,121,63),
        file='./assets/share/event/lucky_draw/LUCKY_DRAW_PAGE.png',
        button=(405,342,478,387)
    )
)
LUCKY_DRAW_POINT=ButtonWrapper(
    name='LUCKY_DRAW_POINT',
    share=Button.default_init(
        area=(544,611,617,631),color=(126,124,100),
        file='./assets/share/event/lucky_draw/LUCKY_DRAW_POINT.png'
    )
)
LUCKY_DRAW_REMAIN=ButtonWrapper(
    name='LUCKY_DRAW_REMAIN',
    share=Button.default_init(
        area=(471,323,489,340),color=(233,82,68),
        file='./assets/share/event/lucky_draw/LUCKY_DRAW_REMAIN.png'
    )
)