import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Alas'
    Scheduler_ServerUpdate = '00:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_GameClient = 'android'
    Emulator_PackageName = 'auto'  # auto, CN-Official, CN-Bilibili
    Emulator_GameLanguage = 'cn'
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy, nemu_ipc, ldopengl
    Emulator_ControlMethod = 'MaaTouch'  # minitouch, MaaTouch
    Emulator_CloudPriorQueue = False
    Emulator_AdbRestart = False

    # Group `EmulatorInfo`
    EmulatorInfo_Emulator = 'auto'  # auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, BlueStacks4HyperV, BlueStacks5HyperV, LDPlayer3, LDPlayer4, LDPlayer9, MuMuPlayer, MuMuPlayerX, MuMuPlayer12, MEmuPlayer
    EmulatorInfo_name = None
    EmulatorInfo_path = None

    # Group `Error`
    Error_Restart = 'game'  # game, game_emulator
    Error_SaveError = True
    Error_ScreenshotLength = 1
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game, close_emulator

    # Group `Reward`
    Reward_Enable = True  # True, False

    # Group `Rescheduler`
    Rescheduler_Enable = True  # True, False

    # Group `QuizCenter`
    QuizCenter_Enable = True  # True, False

    # Group `Competition`
    Competition_Enable = True  # True, False

    # Group `Exercise`
    Exercise_Enable = True  # True, False

    # Group `Expedition`
    Expedition_Enable = True  # True, False

    # Group `DailyRoutine`
    DailyRoutine_Enable = True  # True, False

    # Group `Beach`
    Beach_Enable = True  # True, False

    # Group `TimeOdyssey`
    TimeOdyssey_Enable = True  # True, False

    # Group `DungeonSetting`
    DungeonSetting_BattleField = 'nv1'  # nv1, sv1, ma1, ns1, nv2, sv2, ma2, ns2
    DungeonSetting_ArmTransport = 'a-ng1'  # a-ng1, a-tp1, a-ac1, a-aa1, a-eq1, a-ng2, a-tp2, a-ac2, a-aa2, a-eq2

    # Group `TimeOdysseySetting`
    TimeOdysseySetting_Mode = 'default'  # default, normal, hard, hell, hell_ex
    TimeOdysseySetting_Times = 'default'  # default, 1, 2, 3, max
    TimeOdysseySetting_AutoDecommissioning = False  # True, False
    TimeOdysseySetting_EnableContinuous = False  # True, False
    TimeOdysseySetting_MinimalFuel = 1000

    # Group `TacticalAcademy`
    TacticalAcademy_Enable = True  # True, False
